[project]
name = "open-clio"
version = "0.0.1"
description = "Open-source implementation of CLIO."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=1.0.0",
    "langsmith>=0.4.4",
    "sentence-transformers==2.2.2",
    "scikit-learn>=1.3.0",
    "numpy>=1.21.0,<1.24.0",
    "umap-learn>=0.5.3",
    "kneed>=0.8.5",
    "jupyter>=1.1.1",  
    "plotly>=6.2.0",
    "streamlit>=1.28.0",
    "pandas>=2.0.0",
    "anthropic>=0.55.0",
    "tqdm>=4.65.0",
    "seaborn>=0.13.2",
    "matplotlib>=3.9.4",
    "torch>=1.11.0,<2.0.0",
    "transformers>=4.21.0,<5.0.0",
]
[dependency-groups]
dev = [
    "pandas>=2.0.0",
    "ruff>=0.12.0", 
    "streamlit>=1.28.0",
]
