[project]
name = "open-clio"
version = "0.0.1"
description = "Open-source implementation of CLIO."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=1.0.0",
    "langsmith>=0.4.4",
    "sentence-transformers>=2.2.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    "umap>=0.1.1",
    "kneed>=0.8.5",
    "jupyter>=1.1.1",
    "plotly>=6.2.0",
    "streamlit>=1.46.0",
    "pandas>=2.3.0",
    "anthropic>=0.55.0",
]

[dependency-groups]
dev = [
    "pandas>=2.3.0",
    "ruff>=0.12.0",
    "streamlit>=1.46.0",
]
